/*
    TEMPLATE PLACEHOLDERS

    $variable       INSERTS THE VALUE OF THE VARIABLE INTO THE TEXT
    ${groovycode}   EVALUATES SINGLE LINE GROOVY CODE & INSERTS THE RESULT INTO THE TEXT
    <%=groovycode%> EVALUATE THE GROOVY CODE & INSERT THE RESULT INTO THE TEXT
    <%groovycode%>  EVALUATE THE GROOVY CODE
*/